services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: portfolio:latest
    container_name: portfolio
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "8080:80" # host:container
    restart: unless-stopped
