services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    image: portfolio:latest
    container_name: portfolio
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - "8080:80" # host:container
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/ || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3