name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  workflow_dispatch:  # optional manual trigger (won't run unless you add a manual path)

permissions:
  contents: read
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    # only deploy when triggered by workflow_run AND CI concluded successfully
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    # REQUIRED for actions/deploy-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4